name: know
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  logging: ^1.0.1
  image: ^3.0.2
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - no_insignia.png
    - E2_USAF_AM.svg.png
    - E3_USAF_AM1.svg.png
    - E4_USAF_SAM.svg.png
    - E5_USAF_SSGT.svg.png
    - E6_USAF_TSGT.svg.png
    - E7a_USAF_MSGT.svg.png
    - E8a_USAF_SMSGT.svg.png
    - E9a_USAF_CMSGT.svg.png
    - E9c_USAF_CCMS.svg.png
    - E9d_USAF_CMSAF.svg.png
    - USAF-O1.png
    - USAF-O10.png
    - USAF-O11.png
    - USAF-O2.png
    - USAF-O3.png
    - USAF-O4.png
    - USAF-O5.png
    - USAF-O6.png
    - USAF-O7.png
    - USAF-O8.png
    - USAF-O9.png
    - US-Army-WO1.svg.png
    - US-Army-CW2.svg.png
    - US-Army-CW3.svg.png
    - US-Army-CW4.svg.png
    - US-Army-CW5.svg.png
    - USA-OR-02.svg.png
    - USA-OR-03.svg.png
    - USA-OR-04a-C.svg.png
    - USA-OR-04b-S.svg.png
    - USA-OR-05.svg.png
    - USA-OR-06.svg.png
    - USA-OR-07.svg.png
    - USA-OR-08a-FS.svg.png
    - USA-OR-08b-MS.svg.png
    - USA-OR-09a-SMoA.svg.png
    - USA-OR-09b-CSM.svg.png
    - USA-OR-09c-SM.svg.png
    - US_Navy_OC_shoulderboard.svg.png
    - US_Navy_O1_insignia.svg.png
    - US_Navy_O2_insignia.svg.png
    - US_Navy_O3_insignia.svg.png
    - US_Navy_O4_insignia.svg.png
    - US_Navy_O5_insignia.svg.png
    - US_Navy_O6_insignia.svg.png
    - US_Navy_O7_insignia.svg.png
    - US_Navy_O8_insignia.svg.png
    - US_Navy_O9_insignia.svg.png
    - US_Navy_O10_insignia.svg.png
    - US_Navy_O11_insignia.svg.png
    - US_Navy_Admiral_of_Navy_insignia.svg.png
    - US_Navy_CW2_insignia.svg.png
    - US_Navy_CW3_insignia.svg.png
    - US_Navy_CW4_insignia.svg.png
    - US_Navy_CW5_insignia.svg.png
    - US_Navy_WO1_insignia.svg.png
    - USN_E2_SA.png
    - USN_E3_SM.png
    - USN_E4_PO3.png
    - USN_E5_PO2.png
    - USN_E6_PO1.png
    - USN_E7_CPO.png
    - USN_E8_CMDCS.png
    - USN_E8_SCPO.png
    - USN_E9_CMCPO.png
    - USN_E9_FMCPO.png
    - USN_E9_MCPO.png
    - USN_E9_MCPON.png
    - USMC_WO1.svg.png
    - USMC_CWO2.svg.png
    - USMC_CWO3.svg.png
    - USMC_CWO4.svg.png
    - USMC_CWO5.svg.png
    - USMC-E2.svg.png
    - USMC-E3.svg.png
    - USMC-E4.svg.png
    - USMC-E5.svg.png
    - USMC-E6.svg.png
    - USMC-E7.svg.png
    - USMC-E8-1SG.svg.png
    - USMC-E8-MSG.svg.png
    - USMC-E9-MGyS.svg.png
    - USMC-E9-SGM.svg.png
    - USMC-E9-SGMMC.svg.png
    - USCG_O-1_insignia.svg.png
    - USCG_O-2_insignia.svg.png
    - USCG_O-3_insignia.svg.png
    - USCG_O-4_insignia.svg.png
    - USCG_O-5_insignia.svg.png
    - USCG_O-6_insignia.svg.png
    - USCG_O-7_insignia.svg.png
    - USCG_O-8_insignia.svg.png
    - USCG_O-9_insignia.svg.png
    - USCG_O-10_insignia.svg.png
    - USCG_CW2_insignia.svg.png
    - USCG_CW3_insignia.svg.png
    - USCG_CW4_insignia.svg.png
    - USCG_E1_SR.svg.png
    - USCG_E2_SA.svg.png
    - USCG_E3_SM.svg.png
    - USCG_PO3.png
    - USCG_PO3.svg.png
    - USCG_PO2.png
    - USCG_PO2.svg.png
    - USCG_PO2.png
    - USCG_PO1.svg.png
    - USCG_PO1.png
    - USCG_CPO.png
    - USCG_CPO.svg.png
    - USCG_E2_FA.png
    - USN_E2_SA_collar.png
    - USCG_E2_AA.png
    - USCG_E2_CA.png
    - USN_E3_AM.png
    - USN_E3_FM.png
    - USN_E3_CM.png
    - USN_E3_SM_collar.png
    - USCG_SCPO.png
    - USCG_SCPO.svg.png
    - USCG_MCPO.png
    - USCG_MCPO.svg.png
    - USCG_CMC.svg.png
    - USCG_MCPOCGX.svg.png
    - USCG_MCPOCG.png
    - USCG_MCPOCG.svg.png